//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSI.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientServer
    {
        public System.Guid Id { get; set; }
        public System.Guid ClientId { get; set; }
        public string Environment { get; set; }
        public string ServerAddress { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
