//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSI.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detection
    {
        public Detection()
        {
            this.DetectionImages = new HashSet<DetectionImage>();
        }
    
        public System.Guid Id { get; set; }
        public string TID { get; set; }
        public string Attribute { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ModifiedAt { get; set; }
    
        public virtual ICollection<DetectionImage> DetectionImages { get; set; }
    }
}
