//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSI.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QSIEntities : DbContext
    {
        public QSIEntities()
            : base("name=QSIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Access_Master> Access_Master { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientServer> ClientServers { get; set; }
        public virtual DbSet<DetectionImage> DetectionImages { get; set; }
        public virtual DbSet<Detection> Detections { get; set; }
        public virtual DbSet<ShareWidget> ShareWidgets { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserData> UserDatas { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<UserLogging> UserLoggings { get; set; }
        public virtual DbSet<UserPreference> UserPreferences { get; set; }
        public virtual DbSet<UserSetting> UserSettings { get; set; }
        public virtual DbSet<WorkOrder> WorkOrders { get; set; }
    }
}
