//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSI.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogging
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime LoginDateTime { get; set; }
        public System.DateTime LogoutDateTime { get; set; }
        public bool IsLoggedIn { get; set; }
        public Nullable<System.Guid> Token { get; set; }
        public string Lattitude { get; set; }
        public string Longitude { get; set; }
    
        public virtual User User { get; set; }
    }
}
