//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSI.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ShareWidgets = new HashSet<ShareWidget>();
            this.ShareWidgets1 = new HashSet<ShareWidget>();
            this.UserDatas = new HashSet<UserData>();
            this.UserLoggings = new HashSet<UserLogging>();
            this.UserPreferences = new HashSet<UserPreference>();
            this.WorkOrders = new HashSet<WorkOrder>();
            this.WorkOrders1 = new HashSet<WorkOrder>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string ContactNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public System.Guid UsergroupId { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public bool IsActive { get; set; }
        public System.Guid Token { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ModifiedAt { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.Guid> clientId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<ShareWidget> ShareWidgets { get; set; }
        public virtual ICollection<ShareWidget> ShareWidgets1 { get; set; }
        public virtual UserGroup UserGroup { get; set; }
        public virtual ICollection<UserData> UserDatas { get; set; }
        public virtual ICollection<UserLogging> UserLoggings { get; set; }
        public virtual ICollection<UserPreference> UserPreferences { get; set; }
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
        public virtual ICollection<WorkOrder> WorkOrders1 { get; set; }
    }
}
