//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSI.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public System.Guid Id { get; set; }
        public string WorkOrderName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid AssignedById { get; set; }
        public string AssignedByName { get; set; }
        public string Status { get; set; }
        public string DetectionUrl { get; set; }
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
